server:
  port: 9100

security:
  jwt:
    public-key: classpath:mypublic.txt

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect