server:
  port: 9000

security:
  jwt:
    key-store: classpath:mykeystore.jks
    key-store-password: bista123
    key-pair-alias: servercert
    key-pair-password: bista

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true